### ISSUE TITLE
Risk in production?

### ISSUE THREAD

**Issue by joemasilotti** [kirillplatonov/hotwire-livereload#7]
Is there any risk of adding this to the global Gemfile, outside of development/test?

I see it only has one non-Rails dependency, `listen`, but that is usually reserved for development, only. Does the dependency chain spiral after that or can we assume it is sane?

If not, do you recommend wrapping the tag helper in an `if Rails.env.development?` or similar?

FWIW, I'm wrapping this as follows so I can keep the gem in the development group, only.

```ruby
# app/helpers/application_helper.rb
module ApplicationHelper
  def hotwire_livereload_tags
    super if Rails.env.development?
  end
end
```

**Comment by kirillplatonov** [comment]
It should be safe. The gem has built-in guards to start listening only in development:
https://github.com/kirillplatonov/hotwire-livereload/blob/main/lib/hotwire/livereload/engine.rb#L39

Also, you can remove your custom helper wrapper as the guard in the wrapper is built-in too:
https://github.com/kirillplatonov/hotwire-livereload/blob/main/app/helpers/hotwire/livereload/livereload_tags_helper.rb#L3

**Comment by joemasilotti** [comment]
That's true! I saw that guard in the library. I'm more concerned about bringing in the `listen` gem in production.

**Comment by kirillplatonov** [comment]
I totally get your concern about `listen`. It seems to be safe since the gem won't do anything unless we initialize it and start listening for some folders. And I didn't have any issues with it in production as well. 

But having multiple unused dependencies in production that are intended for development doesn't feel right. I think the best solution would be to install it in the development group, drop helper and use `javascript_include_tag` directly in layout:
```erb
<% if Rails.env.development? %>
  <%= javascript_include_tag "hotwire-livereload", defer: true %>
<% end %>
```

It's a little bit less clean compared to the helper. But still simple enough.

**Comment by joemasilotti** [comment]
Cool, thanks for explaining. I'll stick with my helper above (it keeps the view a tad cleaner) for now. Thanks for the great gem!
